package com.dna.app.domain.taxonomy

/**
 * Controlled vocabulary for dress attributes. Single source of truth — used by:
 *  - Room entities (persistence)
 *  - Firestore DTOs (sync)
 *  - Gemini structured-output schemas (server-side, mirrored in zod)
 *  - UI chip selectors
 *
 * M3b subset. SleeveDetail / Length / Placement / FitType land in M5 when the
 * full generation pipeline needs them.
 */
enum class GarmentType {
    SALWAR_KAMEEZ,
    KURTI,
}

/** Whether a library item is a still image or a video clip. */
enum class MediaType { IMAGE, VIDEO }

enum class Source {
    /** User uploaded a photo of a real dress. */
    UPLOADED,
    /** Generated by the AI pipeline from a fabric + references. */
    GENERATED,
}

enum class SyncState {
    /** Image bytes still uploading, or Firestore write pending. */
    PENDING_UPLOAD,
    /** Room + Firestore agree. */
    SYNCED,
    /** Upload or sync failed; WorkManager will retry. */
    FAILED,
}

enum class Neckline { V, ROUND, BOAT, COLLAR, KEYHOLE, SQUARE, OTHER }

enum class SleeveStyle {
    FULL, THREE_QUARTER, HALF, SHORT, CAP, SLEEVELESS, BELL, OTHER,
}

enum class Silhouette {
    ANARKALI, STRAIGHT, A_LINE, FLARED, PEPLUM, ASYMMETRIC, OTHER,
}

enum class Occasion { CASUAL, OFFICE, FESTIVE, BRIDAL, OTHER }

enum class Embellishment {
    NONE, ZARDOSI, CHIKANKARI, MIRROR, SEQUINS, EMBROIDERY_GENERIC, PRINT, OTHER,
}
