package com.dna.app.domain.taxonomy

/**
 * Controlled vocabulary for dress attributes. Single source of truth — used by:
 *  - Room entities (persistence)
 *  - Firestore DTOs (sync)
 *  - Gemini structured-output schemas (server-side, mirrored in zod)
 *  - UI chip selectors
 *
 * Only the enums needed for M2 (Library grid) are populated. Sleeve / Neckline /
 * Silhouette / Length / Embellishment / Occasion land in M3 when auto-tagging
 * comes online.
 */
enum class GarmentType {
    SALWAR_KAMEEZ,
    KURTI,
}

enum class Source {
    /** User uploaded a photo of a real dress. */
    UPLOADED,
    /** Generated by the AI pipeline from a fabric + references. */
    GENERATED,
}

enum class SyncState {
    /** Image bytes still uploading, or Firestore write pending. */
    PENDING_UPLOAD,
    /** Room + Firestore agree. */
    SYNCED,
    /** Upload or sync failed; WorkManager will retry. */
    FAILED,
}
