package com.dna.app.data.auth

import android.content.Context
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential.Companion.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import dagger.hilt.android.qualifiers.ApplicationContext
import javax.inject.Inject
import javax.inject.Singleton
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.tasks.await

/**
 * Thin wrapper over Firebase Auth + Credential Manager (Google Sign-In).
 *
 * Credential Manager is the modern replacement for GoogleSignInClient (deprecated
 * in 2024). It returns a Google ID token, which we exchange for a Firebase
 * credential.
 */
@Singleton
class AuthRepository @Inject constructor(
    @ApplicationContext private val context: Context,
    private val auth: FirebaseAuth,
) {

    val currentUid: String? get() = auth.currentUser?.uid

    /** Emits the current user's UID (or null) every time auth state changes. */
    fun observeUid(): Flow<String?> = callbackFlow {
        val listener = FirebaseAuth.AuthStateListener { trySend(it.currentUser?.uid) }
        auth.addAuthStateListener(listener)
        awaitClose { auth.removeAuthStateListener(listener) }
    }

    /**
     * Triggers the Google Sign-In sheet and, on success, signs into Firebase
     * with the returned ID token.
     *
     * @param activityContext an Activity context — Credential Manager requires
     *   it to render its bottom-sheet UI.
     */
    suspend fun signInWithGoogle(activityContext: Context) {
        val webClientId = resolveWebClientId()
            ?: throw SignInException(
                "Google Sign-In is not configured. Enable the Google provider in " +
                    "Firebase Console → Authentication → Sign-in method, then " +
                    "re-download google-services.json into app/ and rebuild.",
            )
        val option = GetGoogleIdOption.Builder()
            .setServerClientId(webClientId)
            .setFilterByAuthorizedAccounts(false)
            .setAutoSelectEnabled(true)
            .build()

        val request = GetCredentialRequest.Builder()
            .addCredentialOption(option)
            .build()

        val credentialManager = CredentialManager.create(context)
        val response = try {
            credentialManager.getCredential(activityContext, request)
        } catch (e: GetCredentialException) {
            throw SignInException("Sign-in cancelled or unavailable", e)
        }

        val cred = response.credential
        if (cred !is CustomCredential || cred.type != TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
            throw SignInException("Unexpected credential type: ${cred.type}")
        }
        val googleId = GoogleIdTokenCredential.createFrom(cred.data)
        val firebaseCred = GoogleAuthProvider.getCredential(googleId.idToken, null)
        auth.signInWithCredential(firebaseCred).await()
    }

    /**
     * Looks up `default_web_client_id` — auto-generated by the google-services
     * plugin once the Google Sign-In provider is enabled in Firebase Console.
     * Returns null if it hasn't been generated yet, so the build still succeeds
     * before auth is fully configured.
     */
    private fun resolveWebClientId(): String? {
        val resId = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName,
        )
        return if (resId == 0) null else context.getString(resId)
    }

    suspend fun signOut() {
        auth.signOut()
        // Credential Manager has no explicit sign-out; on next getCredential the
        // user picks again.
    }
}

class SignInException(msg: String, cause: Throwable? = null) : RuntimeException(msg, cause)
